In [14]:
from components.HarvestWorld import HarvestWorld

from importlib import import_module, reload

import ipywidgets as widgets

import matplotlib.pyplot as plt
from IPython.display import clear_output

harvest_world_module = import_module('components.HarvestWorld')
reload(harvest_world_module)

<module 'components.HarvestWorld' from '/home/raul/Escritorio/extra/misis/rl/rl_uniandes/dynamic_actions/components/HarvestWorld.py'>

In [15]:
ASCII_MAP = """
AA   AA
A  Q  A
"""

harvest_world = HarvestWorld(ASCII_MAP, 
                            regrowth_probs=[0.0, 0.005],
                            num_agents=1)
    

In [16]:
def update_plot(freq):
    clear_output(wait=True)
    fig, axes = plt.subplots(1, 2, figsize=(20, 15))
    harvest_world.plot_map(axes[0])
    harvest_world.agents[0].plot_knowledge(axes[1])
    harvest_world.advance_timestep()
    plt.show() 
    
freq_slider = widgets.FloatSlider(value=0, min=0, max=10, step=1, description='Frequency:')
out = widgets.interactive_output(update_plot, {'freq': freq_slider})
display(freq_slider, out)

FloatSlider(value=0.0, description='Frequency:', max=10.0, step=1.0)

Output()

In [17]:
harvest_world.agents[0].q_knowledge[(1,1)]

{}

In [18]:
harvest_world.agents[0].q_knowledge[(1,0)]

{}

In [19]:
harvest_world.agents[0].current_state

(1, 3)

In [20]:
import numpy as np

In [21]:
q_table = np.random.uniform(low=0, high=1, size= (2,7,4))
q_table

array([[[0.01971398, 0.78622886, 0.461944  , 0.33238658],
        [0.88569384, 0.41074427, 0.82439332, 0.34628488],
        [0.63518839, 0.93502571, 0.19396245, 0.53055357],
        [0.45005431, 0.55740123, 0.15784399, 0.58250666],
        [0.84269429, 0.75482235, 0.68074531, 0.65072452],
        [0.45293903, 0.1759909 , 0.74067551, 0.32897443],
        [0.38026206, 0.64733013, 0.48808244, 0.77012329]],

       [[0.66322051, 0.55813661, 0.22844383, 0.01712036],
        [0.39828807, 0.12022861, 0.8776355 , 0.62919292],
        [0.38500662, 0.21781892, 0.03977376, 0.98034649],
        [0.99872493, 0.29620194, 0.08867212, 0.25468887],
        [0.72035683, 0.13835271, 0.69597843, 0.96988991],
        [0.56614769, 0.73224348, 0.52700228, 0.03578017],
        [0.94389726, 0.08999894, 0.31087094, 0.06840179]]])

In [22]:
q_table.shape

(2, 7, 4)

In [23]:
np.argmax(q_table[(0,0)])

1

In [24]:
q_table[(0,0)]

array([0.01971398, 0.78622886, 0.461944  , 0.33238658])

In [25]:
q_table[(1,2)]

array([0.38500662, 0.21781892, 0.03977376, 0.98034649])

In [26]:
np.max(q_table[(0,0)])

0.7862288627775849