In [1]:
from components.HarvestWorld import HarvestWorld

from importlib import import_module, reload

import ipywidgets as widgets

import matplotlib.pyplot as plt
from IPython.display import clear_output

harvest_world_module = import_module('components.HarvestWorld')
reload(harvest_world_module)

<module 'components.HarvestWorld' from '/home/raul/Escritorio/extra/misis/rl/rl_uniandes/dynamic_actions/components/HarvestWorld.py'>

In [2]:
ASCII_MAP = """
A  W  A
AA WW  
A   W Q
"""

harvest_world = HarvestWorld(ASCII_MAP, 
                            regrowth_probs=[0.0, 0.005],
                            num_agents=1)
    

In [3]:
def update_plot(freq):
    clear_output(wait=True)
    fig, axes = plt.subplots(1, 2, figsize=(20, 15))
    harvest_world.plot_map(axes[0])
    harvest_world.agents[0].plot_knowledge(axes[1])
    harvest_world.advance_timestep()
    plt.show() 
    
freq_slider = widgets.FloatSlider(value=0, min=0, max=10, step=1, description='Frequency:')
out = widgets.interactive_output(update_plot, {'freq': freq_slider})
display(freq_slider, out)

FloatSlider(value=0.0, description='Frequency:', max=10.0, step=1.0)

Output()

In [4]:
harvest_world.agents[0].q_knowledge[(1,1)]

{}

In [5]:
harvest_world.agents[0].q_knowledge[(1,0)]

{}

In [6]:
harvest_world.agents[0].current_state

(2, 6)

In [7]:
import numpy as np

In [8]:
q_table = np.random.uniform(low=0, high=1, size= (2,7,4))
q_table

array([[[0.12011013, 0.11967254, 0.02926843, 0.52267857],
        [0.95721941, 0.39786279, 0.13907273, 0.59370368],
        [0.39430193, 0.97243407, 0.00813345, 0.24049176],
        [0.37673942, 0.25286051, 0.96813366, 0.34769002],
        [0.95710314, 0.74457131, 0.21726346, 0.291498  ],
        [0.69523621, 0.29446093, 0.20962909, 0.04473997],
        [0.98129213, 0.89759953, 0.20097734, 0.42609198]],

       [[0.45892319, 0.74676757, 0.47949569, 0.04253374],
        [0.30462715, 0.75431862, 0.56527031, 0.02425262],
        [0.98441154, 0.68849293, 0.59726592, 0.58810603],
        [0.27883852, 0.91472854, 0.87827877, 0.12831872],
        [0.9068797 , 0.95014128, 0.6170354 , 0.03502651],
        [0.06954405, 0.24397045, 0.09281627, 0.69291925],
        [0.91359709, 0.89803442, 0.38287895, 0.21268833]]])

In [9]:
q_table.shape

(2, 7, 4)

In [10]:
np.argmax(q_table[(0,0)])

3

In [11]:
q_table[(0,0)]

array([0.12011013, 0.11967254, 0.02926843, 0.52267857])

In [12]:
q_table[(1,2)]

array([0.98441154, 0.68849293, 0.59726592, 0.58810603])

In [13]:
np.max(q_table[(0,0)])

0.5226785650944072